### PR TITLE
Updated Skylark uploaders readme

### PR DESCRIPTION
**Pull request by Xemuth**

### CODE REVIEW

**Comment by mirek-fidler** [comment]
Sorry, but are we sure this belongs to UppHub?

Best use would be to make this Codeproject article...

Mirek

**Comment by Xemuth** [comment]
@mirek-fidler  It is as you wish, however from my point of view, this app is nothing fancy but just a demo of Skylark

**Comment by mirek-fidler** [comment]
If it is demo of skylark, then it should be in skylark/examples....

**Comment by ismail-yilmaz** [comment]
@mirek-fidler , @Xemuth OK, I am going to remove this demo app from the main UppHub tree. If no objections.
Reason: The pull request should be made for [Skylark repo](https://github.com/mirek-fidler/Skylark).

**Comment by Xemuth** [comment]
No objection for me, I can do the PR again for Skylark examples however, if you think the app should not be in UppHub then it's ok for me too. It's up to you

**Comment by ismail-yilmaz** [comment]
@Xemuth 

OK, then. Let's do it that way and keep UppHub module-only. The demo is very nice, and IMO, as Mirek suggests, it would be a good source material for a CodeProject article.

> No objection for me, I can do the PR again for Skylark examples however, if you think the app should not be in UppHub then it's ok for me too. It's up to you

**Comment by mirek-fidler** [comment]
Just to be sure that we understand each other: I believe this should be
part of Skylark UppHub module, in examples subfolder.

See e.g. https://github.com/mirek-fidler/urr

Mirek

**Pull request merged**
